# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  zookeeper-prestacaodeservico:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000